/**
 * LLM Inference Full Video with Voiceover
 *
 * Complete ~3 minute explainer video with narration.
 * Uses audio files generated by Edge TTS.
 */

import React from "react";
import {
  AbsoluteFill,
  Sequence,
  Audio,
  staticFile,
  useVideoConfig,
  interpolate,
  useCurrentFrame,
} from "remotion";

import { Scene1Hook } from "./Scene1Hook";
import { Scene2Phases } from "./Scene2Phases";
import { Scene3Bottleneck } from "./Scene3Bottleneck";
import { Scene4Attention } from "./Scene4Attention";
import { Scene5Redundancy } from "./Scene5Redundancy";
import { Scene6KVCache } from "./Scene6KVCache";
import { Scene7Mechanics } from "./Scene7Mechanics";
import { Scene8Impact } from "./Scene8Impact";

// Scene configuration with audio durations (from voiceover manifest)
// Audio files are in remotion/public/voiceover/ (staticFile serves from public/)
const SCENES_WITH_AUDIO = [
  {
    id: "hook",
    component: Scene1Hook,
    audioFile: "voiceover/scene1_hook.mp3",
    audioDuration: 21.16,
  },
  {
    id: "phases",
    component: Scene2Phases,
    audioFile: "voiceover/scene2_phases.mp3",
    audioDuration: 21.61,
  },
  {
    id: "bottleneck",
    component: Scene3Bottleneck,
    audioFile: "voiceover/scene3_bottleneck.mp3",
    audioDuration: 24.30,
  },
  {
    id: "attention",
    component: Scene4Attention,
    audioFile: "voiceover/scene4_attention.mp3",
    audioDuration: 22.48,
  },
  {
    id: "redundancy",
    component: Scene5Redundancy,
    audioFile: "voiceover/scene5_redundancy.mp3",
    audioDuration: 29.62,
  },
  {
    id: "kvcache",
    component: Scene6KVCache,
    audioFile: "voiceover/scene6_kvcache.mp3",
    audioDuration: 22.41,
  },
  {
    id: "mechanics",
    component: Scene7Mechanics,
    audioFile: "voiceover/scene7_mechanics.mp3",
    audioDuration: 20.40,
  },
  {
    id: "impact",
    component: Scene8Impact,
    audioFile: "voiceover/scene8_impact.mp3",
    audioDuration: 31.30,
  },
] as const;

// Buffer time between scenes (seconds)
const SCENE_BUFFER = 1.0;

// Transition duration in seconds
const TRANSITION_DURATION = 0.5;

interface LLMInferenceWithAudioProps {
  /** Use static file paths for audio (for rendering) */
  useStaticAudio?: boolean;
}

/**
 * Fade transition component
 */
const FadeTransition: React.FC<{
  children: React.ReactNode;
  durationInFrames: number;
}> = ({ children, durationInFrames }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const transitionFrames = Math.floor(TRANSITION_DURATION * fps);

  // Fade in at start
  const fadeIn = interpolate(frame, [0, transitionFrames], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Fade out at end
  const fadeOut = interpolate(
    frame,
    [durationInFrames - transitionFrames, durationInFrames],
    [1, 0],
    {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    }
  );

  const opacity = Math.min(fadeIn, fadeOut);

  return <div style={{ opacity }}>{children}</div>;
};

export const LLMInferenceWithAudio: React.FC<LLMInferenceWithAudioProps> = ({
  useStaticAudio = true,
}) => {
  const { fps } = useVideoConfig();

  // Calculate frame offsets for each scene
  let currentFrame = 0;
  const sceneData = SCENES_WITH_AUDIO.map((scene) => {
    const startFrame = currentFrame;
    // Scene duration = audio duration + buffer
    const durationSeconds = scene.audioDuration + SCENE_BUFFER;
    const durationInFrames = Math.ceil(durationSeconds * fps);
    currentFrame += durationInFrames;

    return {
      ...scene,
      startFrame,
      durationInFrames,
      durationSeconds,
    };
  });

  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#0f0f1a",
      }}
    >
      {sceneData.map((scene, index) => {
        const SceneComponent = scene.component;

        return (
          <Sequence
            key={scene.id}
            from={scene.startFrame}
            durationInFrames={scene.durationInFrames}
            name={`Scene ${index + 1}: ${scene.id}`}
          >
            {/* Visual content with fade transition */}
            <FadeTransition durationInFrames={scene.durationInFrames}>
              <SceneComponent />
            </FadeTransition>

            {/* Audio track */}
            {useStaticAudio && (
              <Audio
                src={staticFile(scene.audioFile)}
                volume={1}
              />
            )}
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};

// Export total duration for composition registration
export const TOTAL_DURATION_WITH_AUDIO = SCENES_WITH_AUDIO.reduce(
  (sum, scene) => sum + scene.audioDuration + SCENE_BUFFER,
  0
);

// Export scene metadata
export const AUDIO_SCENE_METADATA = SCENES_WITH_AUDIO.map((scene, index) => ({
  index,
  id: scene.id,
  audioFile: scene.audioFile,
  audioDuration: scene.audioDuration,
}));

export default LLMInferenceWithAudio;
